In [23]:
import os              # module for interacting with the operating system
import xarray as xr    # THIS IS THE LIBRARY WE WILL BE EXPLORING

import numpy as np

# Creating an xarray.DataArray

hese variables have an associated meaning: they describe constant/fixed/independent quantities, unlike the varying/measured/dependent quantities that belong in variables. 

In [53]:
# values of a single variable at each point of the coords (it's a numpy.ndarray)

prec_data = np.array([np.zeros((5,5)), 
                      np.ones((5,5)), 
                      np.ones((5,5))*2]).astype(int)
print(prec_data.shape)
prec_data

(3, 5, 5)


array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])

In [57]:
# names of the data dimensions (tuple of strings)
dims = ('day', 'x', 'y')

# coordinates (tick labels) to use for indexing along each dimension (dictionary)
coords = {'day' : [1, 2, 3],
          'x' : np.arange(10,60,10),
          'y' : np.arange(30,80,10)}  

# attributes (metadata) of the data array (it's a dictionary)
attrs = { 'title' : 'precipitation data on days 1, 2, and 3',
          'units' : 'mm'}

# initialize xarray.DataArray
prec = xr.DataArray(data = prec_data, 
                    dims = dims,
                    coords = coords,
                    attrs = attrs)
prec

<xarray.DataArray (day: 3, lat: 5, lon: 5)>
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * day      (day) int64 1 2 3
  * lat      (lat) int64 10 20 30 40 50
  * lon      (lon) int64 30 40 50 60 70
Attributes:
    title:    precipitation data on days 1, 2, and 3
    units:    ml / pixel

In [58]:
# we can also update the attributes (metadata) after creating the set
prec.attrs['description'] = 'a small example of an xarray.DataArray'

# each of the coordinates is also an xarray.DataArray
# so we can add attributes to coordinates 
prec.day.attrs = {'standard_name':'day of collection'}

prec.lat.attrs['standard_name']= 'latitude'
prec.lat.attrs['units'] = 'degrees_north'

prec.lon.attrs['standard_name']= 'longitude'
prec.lon.attrs['units'] = 'degrees_east'
prec

<xarray.DataArray (day: 3, lat: 5, lon: 5)>
array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2]]])
Coordinates:
  * day      (day) int64 1 2 3
  * lat      (lat) int64 10 20 30 40 50
  * lon      (lon) int64 30 40 50 60 70
Attributes:
    title:        precipitation data on days 1, 2, and 3
    units:        ml / pixel
    description:  a small example of an xarray.DataArray

## Indexing
READ MORE @ https://docs.xarray.dev/en/stable/user-guide/indexing.html

In [17]:
# multi_day_prec[multi_day_prec.doc == 2]

In [18]:
# multi_day_prec[multi_day_prec.doc == 2]

## Computation
https://rabernat.github.io/research_computing_2018/xarray.html

## Reductions
We can reduce xarray DataArrays along any number of axes:

In [59]:
avg_prec = prec.mean(dim = 'day') # to keep attributes add keep_attrs = True

avg_prec.attrs = {'title':'average precipitation over three days',
                  'units': 'mm/*'}
avg_prec

<xarray.DataArray (lat: 5, lon: 5)>
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
Coordinates:
  * lat      (lat) int64 10 20 30 40 50
  * lon      (lon) int64 30 40 50 60 70
Attributes:
    title:    average precipitation over three days
    units:    ml/pixel per day

In [62]:
# Q: how would you find the average prec of all plots in a single day?
avg_prec = prec.mean(dim = ['lat','lon']) # to keep attributes add keep_attrs = True
avg_prec

<xarray.DataArray (day: 3)>
array([0., 1., 2.])
Coordinates:
  * day      (day) int64 1 2 3

# Creating an xarray.DataSet
https://docs.xarray.dev/en/stable/generated/xarray.Dataset.html

A multi-dimensional, in memory, array database.

A dataset resembles an in-memory representation of a NetCDF file, and consists of variables, coordinates and attributes which together form a self describing dataset.

In [86]:
prec_data = xr.Dataset( data_vars = {'avg_prec': avg_prec,
                                     'prec': prec},
                        attrs = {'creator_name':'Carmen GG', 
                                 'title':'mock precipitation data',
                                 'description':'a simple example of an xarray.Dataset'})
prec_data

<xarray.Dataset>
Dimensions:   (day: 3, lat: 5, lon: 5)
Coordinates:
  * day       (day) int64 1 2 3
  * lat       (lat) int64 10 20 30 40 50
  * lon       (lon) int64 30 40 50 60 70
Data variables:
    avg_prec  (day) float64 0.0 1.0 2.0
    prec      (day, lat, lon) int64 0 0 0 0 0 0 0 0 0 0 ... 2 2 2 2 2 2 2 2 2 2
Attributes:
    creator_name:  Carmen GG
    title:         mock precipitation data
    description:   a simple example of an xarray.Dataset

## Indexing

In [69]:
prec_data.avg_prec

<xarray.DataArray 'avg_prec' (day: 3)>
array([0., 1., 2.])
Coordinates:
  * day      (day) int64 1 2 3

## Save and reopen

In [64]:
fp = os.path.join(os.getcwd(),'prec_data.nc')
prec_data.to_netcdf(fp)

# open to check:
check_prec = xr.open_dataset(fp)
check_prec

<xarray.Dataset>
Dimensions:   (lat: 2, lon: 2, day: 3)
Coordinates:
  * lat       (lat) int64 10 20
  * lon       (lon) int64 30 40
  * day       (day) int64 1 2 3
Data variables:
    avg_prec  (lat, lon) float64 ...
    prec      (day, lat, lon) int64 ...
Attributes:
    creator_name:  Carmen GG
    title:         precipitation data
    description:   a simple example of an xarray.Dataset

# Exercise 1

https://arcticdata.io/catalog/view/doi%3A10.18739%2FA2280504J

In [70]:
fp = os.path.join(os.getcwd(), 'FW_data_CESM_LW_2006_2100.nc')
fw_data = xr.open_dataset(fp)
fw_data
#netPrec_annual

<xarray.Dataset>
Dimensions:                          (time: 95, member: 11)
Coordinates:
  * time                             (time) float64 2.006e+03 ... 2.1e+03
  * member                           (member) float64 1.0 2.0 3.0 ... 10.0 11.0
Data variables: (12/16)
    FW_flux_Fram_annual_net          (time, member) float64 ...
    FW_flux_Barrow_annual_net        (time, member) float64 ...
    FW_flux_Nares_annual_net         (time, member) float64 ...
    FW_flux_Davis_annual_net         (time, member) float64 ...
    FW_flux_BSO_annual_net           (time, member) float64 ...
    FW_flux_Bering_annual_net        (time, member) float64 ...
    ...                               ...
    Solid_FW_flux_BSO_annual_net     (time, member) float64 ...
    Solid_FW_flux_Bering_annual_net  (time, member) float64 ...
    runoff_annual                    (time, member) float64 ...
    netPrec_annual                   (time, member) float64 ...
    Liquid_FW_storage_Arctic_annual  (time, member) float64 ...
    Solid_FW_storage_Arctic_annual   (time, member) float64 ...
Attributes:
    creation_date:   02-Jun-2020 15:38:31
    author:          Alexandra Jahn, CU Boulder, alexandra.jahn@colorado.edu
    title:           Annual timeseries of freshwater data from the CESM Low W...
    description:     Annual mean Freshwater (FW) fluxes and storage relative ...
    data_structure:  The data structure is |Ensemble member | Time (in years)...

In [81]:
fw_data.attrs.keys()

dict_keys(['creation_date', 'author', 'title', 'description', 'data_structure'])

## Exercise 2:

https://arcticdata.io/catalog/view/doi:10.18739/A26T0GX63

In [83]:
fp = os.path.join(os.getcwd(), 'SALT.0001.nc')
data = xr.open_dataset(fp)
data

<xarray.Dataset>
Dimensions:  (i1: 12, i2: 83, i3: 90, i4: 90)
Coordinates:
  * i1       (i1) float64 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0 12.0
  * i2       (i2) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 79.0 80.0 81.0 82.0 83.0
  * i3       (i3) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 86.0 87.0 88.0 89.0 90.0
  * i4       (i4) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 86.0 87.0 88.0 89.0 90.0
    lon      (i3, i4) float64 ...
    lat      (i3, i4) float64 ...
    dep      (i2) float64 ...
    tim      (i1) datetime64[ns] ...
Data variables:
    SALT     (i1, i2, i3, i4) float32 ...
    timstep  (i1) float64 ...
    land     (i2, i3, i4) float64 ...
    area     (i3, i4) float64 ...
    thic     (i2) float64 ...
Attributes:
    Description:     High resolution 3.5km run
    Institution:     Oden Institute for Computational Engineering and Science...
    References:        
    01:                 Nguyen, A.T., 2022.
    Conventions:     CF-1.6 (http://cfconventions.org/cf-conventions/v1.6.0/c...
    Software:        File created using convert_ASTE2nctiles_DIAG_hires_f3.m
    netCDF Version:  4.7.4
    matlab Version:  9.11.0.1809720 (R2021b) Update 1
    _FillValue:      nan
    missing_value:   nan

In [85]:
data.lon

<xarray.DataArray 'lon' (i3: 90, i4: 90)>
array([[ 0.      ,  0.      ,  0.      , ..., 55.871243, 55.931644, 55.992298],
       [ 0.      ,  0.      ,  0.      , ..., 55.840996, 55.901318, 55.961891],
       [ 0.      ,  0.      ,  0.      , ..., 55.809994, 55.870235, 55.930729],
       ...,
       [48.128757, 48.159004, 48.190006, ..., 52.      , 52.057346, 52.114964],
       [48.068356, 48.098682, 48.129765, ..., 51.942654, 52.      , 52.057617],
       [48.007702, 48.038109, 48.069271, ..., 51.885036, 51.942383, 52.      ]])
Coordinates:
  * i3       (i3) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 86.0 87.0 88.0 89.0 90.0
  * i4       (i4) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 86.0 87.0 88.0 89.0 90.0
    lon      (i3, i4) float64 0.0 0.0 0.0 0.0 0.0 ... 51.83 51.89 51.94 52.0
    lat      (i3, i4) float64 0.0 0.0 0.0 0.0 0.0 ... 70.14 70.16 70.18 70.19
Attributes:
    long_name:      longitude
    standard_name:  longitude
    units:          degrees_east

# TO DO:
add intro example -> natural way to package: NetCDF -> NetCDF Data Model -> xarray to work/create NetCDF files
Flesh out exercises 1 and 2