In [1]:
import os              # module for interacting with the operating system
import xarray as xr    # THIS IS THE LIBRARY WE WILL BE EXPLORING

import numpy as np

In [2]:
#https://databasin.org/datasets/901304723480477baf71cc669bf0714f/

In [3]:
# fp = os.path.join(os.getcwd(), 'SALT.0001.nc')

In [4]:
# data = xr.open_dataset(fp)
# data

In [5]:
# data.i4

In [6]:
# data.lat.data.shape

In [7]:
# data.i1

In [8]:
# data.lon

In [9]:
# fp = os.path.join(os.getcwd(), 'FW_data_CESM_LW_2006_2100.nc')
# xr.open_dataset(fp)

In [10]:
# fp = os.path.join(os.getcwd(), 'historic_ppt.nc')
# xr.open_dataset(fp)

## Example 0: creating a 2-dimensional xarray.DataArray

In [11]:
# values of a single variable at each point of the coords (it's a numpy.ndarray)
sdp_data = np.array([[1,2],[0,1]])  

# names of the data dimensions (tuple of strings)
dims = ('lat','lon')        

# coordinates (tick labels) to use for indexing along each dimension (it's a dictionary)
coords = {'lat' : [10, 20],
          'lon' : [30, 40]}   

# attributes (metadata) of the data array (it's a dictionary)
attrs = { 'creator_name': 'Carmen GG', 
          'title' : 'single day precipitation',
          'units' : 'ml / pixel'}

In [12]:
sdp = xr.DataArray(data = sdp_data, 
                    dims = dims,
                    coords = coords,
                    attrs = attrs)
sdp

<xarray.DataArray (lat: 2, lon: 2)>
array([[1, 2],
       [0, 1]])
Coordinates:
  * lat      (lat) int64 10 20
  * lon      (lon) int64 30 40
Attributes:
    creator_name:  Carmen GG
    title:         single day precipitation
    units:         ml / pixel

In [13]:
# we can also update the attributes (metadata) after creating the set
sdp.attrs['description'] = 'this is a small example to understand how to create an xarray datarray'

# each of the coordinates is also an xarray.DataArra
# so we can add attributes to coordinates 
sdp.lat.attrs['standard_name']= 'latitude'
sdp.lat.attrs['units'] = 'degrees_north'

sdp.lon.attrs['standard_name']= 'longitude'
sdp.lon.attrs['units'] = 'degrees_east'
sdp

<xarray.DataArray (lat: 2, lon: 2)>
array([[1, 2],
       [0, 1]])
Coordinates:
  * lat      (lat) int64 10 20
  * lon      (lon) int64 30 40
Attributes:
    creator_name:  Carmen GG
    title:         single day precipitation
    units:         ml / pixel
    description:   this is a small example to understand how to create an xar...

## Example 2: adding one more dimension

In [14]:
# suppose we take measurements for precipitation on 3 days
mdp_data = np.array([[[1,2],[0,1]],
                      [[2,2],[2,2]],
                      [[0,0],[0,0]]
                     ])
mdp_data[0]

array([[1, 2],
       [0, 1]])

In [18]:
# dimensions
dims = ('day', 'lat', 'lon')

# coordinates (tick labels) to use for indexing along each dimension (dictionary)
coords = {'day' : [1,2,3],
          'lat' : [10, 20],
          'lon' : [30, 40]} 

mdp = xr.DataArray(data = mdp_data,
                              dims = dims,
                              coords = coords, 
                              attrs = sdp.attrs)

mdp.lat.attrs = sdp.lat.attrs
mdp.lon.attrs = sdp.lon.attrs
mdp.day.attrs = {'standard_name':'day of collection'}
mdp

<xarray.DataArray (day: 3, lat: 2, lon: 2)>
array([[[1, 2],
        [0, 1]],

       [[2, 2],
        [2, 2]],

       [[0, 0],
        [0, 0]]])
Coordinates:
  * day      (day) int64 1 2 3
  * lat      (lat) int64 10 20
  * lon      (lon) int64 30 40
Attributes:
    creator_name:  Carmen GG
    title:         single day precipitation
    units:         ml / pixel
    description:   this is a small example to understand how to create an xar...

In [20]:
# update title
mdp.attrs['title'] = 'precipitation data on days 1, 2, and 3'
mdp.attrs['title']

'precipitation data on days 1, 2, and 3'

In [21]:
mdp

<xarray.DataArray (day: 3, lat: 2, lon: 2)>
array([[[1, 2],
        [0, 1]],

       [[2, 2],
        [2, 2]],

       [[0, 0],
        [0, 0]]])
Coordinates:
  * day      (day) int64 1 2 3
  * lat      (lat) int64 10 20
  * lon      (lon) int64 30 40
Attributes:
    creator_name:  Carmen GG
    title:         precipitation data on days 1, 2, and 3
    units:         ml / pixel
    description:   this is a small example to understand how to create an xar...

### 

## Indexing using dimension names
READ MORE @ https://docs.xarray.dev/en/stable/user-guide/indexing.html

In [ ]:
multi_day_prec[multi_day_prec.doc == 2]

In [ ]:
multi_day_prec[multi_day_prec.doc == 2]

In [ ]:
avg_p = mdp.mean(dim = 'doc')  # to keep attributes add keep_attrs = True
avg_p

In [ ]:
multi_day_temp = mutli_day_prec.copy(np.random.rand(3,2,2)*100)
multi_day_temp

In [ ]:
?mutli_day_prec