In [2]:
import numpy as np

In [5]:
a = np.array(range(0,25)).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
avg = conf2D(a, weights=w)
avg

array([[ 2,  2,  3,  4,  5],
       [ 5,  5,  6,  8,  8],
       [10, 11, 12, 13, 13],
       [15, 15, 17, 18, 18],
       [18, 19, 20, 21, 22]])

In [16]:
mins

array([[ 0,  0,  1,  2,  3],
       [ 0,  0,  1,  2,  3],
       [ 5,  5,  6,  7,  8],
       [10, 10, 11, 12, 13],
       [15, 15, 16, 17, 18]])

In [19]:
maxs

array([[ 6,  7,  8,  9,  9],
       [11, 12, 13, 14, 14],
       [16, 17, 18, 19, 19],
       [21, 22, 23, 24, 24],
       [21, 22, 23, 24, 24]])

In [20]:
from scipy.ndimage import maximum_filter as maxf2D
from scipy.ndimage import minimum_filter as minf2D
# https://stackoverflow.com/questions/43966350/getting-the-maximum-in-each-rolling-window-of-a-2d-numpy-array

In [9]:
# Store shapes of inputs
M = 3 #window size
N = 3
P,Q = a.shape
Q

5

In [18]:
# Use 2D max filter and slice out elements not affected by boundary conditions
maxs = maxf2D(a, size=(M,N))
max_Map_Out

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [15]:
# Use 2D max filter and slice out elements not affected by boundary conditions
mins = minf2D(a, size=(M,N))
min_Map_Out = mins[M//2:(M//2)+P-M+1, N//2:(N//2)+Q-N+1]
min_Map_Out

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [21]:
from scipy.ndimage import convolve as conf2D

In [25]:
w = np.ones(9).reshape(3,3)/9
w

array([[0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111],
       [0.11111111, 0.11111111, 0.11111111]])