In [2]:
import numpy as np

In [20]:
from scipy.ndimage import maximum_filter as maxf2D
from scipy.ndimage import minimum_filter as minf2D
from scipy.ndimage import convolve as conf2D
# https://stackoverflow.com/questions/43966350/getting-the-maximum-in-each-rolling-window-of-a-2d-numpy-array

In [5]:
a = np.array(range(0,25)).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
# Store shapes of inputs
M = 3 #window size
N = 3
P,Q = a.shape

5

In [18]:
maxs = maxf2D(a, size=(M,N))
maxs

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [15]:

mins = minf2D(a, size=(M,N))
mi

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [38]:
w = np.ones(9).reshape(3,3)
w

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
avg = conf2D(a, weights=w,
            mode='constant')
avg/9

array([[ 1.33333333,  2.33333333,  3.        ,  3.66666667,  2.66666667],
       [ 3.66666667,  6.        ,  7.        ,  8.        ,  5.66666667],
       [ 7.        , 11.        , 12.        , 13.        ,  9.        ],
       [10.33333333, 16.        , 17.        , 18.        , 12.33333333],
       [ 8.        , 12.33333333, 13.        , 13.66666667,  9.33333333]])

In [40]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])